name: Medical_Expenses

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permission:
    content: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/checkout@v3
              with:
                  python-version: "3.12"